CXX = g++
override CXX_VERSION = -std=c++17
override CXX_FLAGS += -c
WARNINGS = -Wall -Wpedantic -Wextra
TESTFILE = TestCase.txt

Target = mainExe				
TARGET_DEL = mainExe.exe


SRCS = main.cpp Data.cpp VetPetInfo.txt
OBJS = Data.obj LinkedList.obj 

all: $(TARGET) run


$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

run: $(TARGET)
	$(TARGET)

clean:
	del $(TARGET_DEL) $(OBJS)